[[PortingKettlePlugins-PortingKettlePlugins]]
= Porting Kettle Plugins

== Change maven dependencies

You no longer need a Pentaho specific *$HOME/.m2/settings.xml*

- Change group *pentaho-kettle* to *org.hop*
- Change dependency *kettle-core* to *hop-core*
- Change dependency *kettle-engine* to *hop-engine*
- Change dependency *kettle-ui-swt* to *hop-ui-swt*

== API changes

=== Interface naming

All interface classes have changed from <Name>Interface to I<Name>.
For example: *RowMetaInterface -> IRowMeta*

=== Transformations

Transformations are now called Pipelines.  This means that the corresponding classes have changed.

For example:
- TransMeta is now called *PipelineMeta*
- Trans is now called *Pipeline*

=== Steps

Steps are now called Transforms.  For example:

- StepMeta is now called *TransformMeta*
- StepMetaInterface is now called *ITransformMeta*
- BaseStep is now called *BaseTransform*
- StepDataInterface is now called *ITransformData*

...and so on

=== Transform Generics

ITransform no longer expects you to pass ITransformMeta and ITransformData classes in the following methods:

- processRow()
- init()
- dispose()
- stopRunning()

This greatly simplifies the code.
Your need to let Hop know what the relationship is between your implementation of ITransform, ITransformMeta, ITransformData, for example:

```
public class Sample extends BaseTransform<SampleMeta, SampleData> implements ITransform<SampleMeta, SampleData> {

 ...

}
```

The same is true for your implementation of ITransformMeta:

```
public class SampleMeta extends BaseTransformMeta implements ITransformMeta<Sample, SampleData> {

 ...

}
```
